In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [3]:
array1_inv = np.linalg.inv(array1)
X = (array1_inv @ array1)
np.array_equal(X,np.identity(2))

False

In [4]:
eigenvalue, eigenvector = np.linalg.eig(array1)
eigenvalue,eigenvector

(array([13.,  2.]),
 array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [5]:
u, s, vh = np.linalg.svd(array1)
u, s, vh

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))